version: '3.8'

services:
  controle_gestual:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/root/ros2_ws
      - /dev/video2:/dev/video2
    devices:
      - /dev/video2:/dev/video2
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true